export const COMMANDS = {
  GET_VENDORS: 'GET_VENDORS',
  EXPLORE: 'EXPLORE',
  PARSE: 'PARSE',
  MERGE: 'MERGE',
  TAG: 'TAG',
  GET_GALLERY: 'GET_GALLERY',
};

export const PARSE_MSGS = {
  SUCCESS: 'SUCCESS',
  NEW_VENDOR: 'NEW_VENDOR',
  ERROR: 'ERROR',
  DELETED: 'DELETED',
  MULTIPLE_MATCHES: 'MULTIPLE_MATCHES',
  DONE: 'DONE',
};
